apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
  namespace: default
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: >-
            719012679654.dkr.ecr.eu-central-1.amazonaws.com/demo:1.0.0
          ports:
            - name: business
              containerPort: 8080
            - name: jmx
              containerPort: 9090
          imagePullPolicy: Always
          env:
            - name: SPRING_SETTINGS
              valueFrom:
                configMapKeyRef:
                  name: global-eviroments
                  key: env
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: jmx
            initialDelaySeconds: 90
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: jmx
            initialDelaySeconds: 90
            periodSeconds: 10
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 400Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /mnt/log
              name: log-pvc
      imagePullSecrets:
        - name: aws-registry
      volumes:
        - name: log-pvc
          persistentVolumeClaim:
            claimName: log-claim
